name: satisfia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.4
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - readline=8.2
  - setuptools=70.3.0
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
    - beartype==0.18.5
    - cloudpickle==3.0.0
    - farama-notifications==0.0.4
    - filelock==3.15.4
    - fsspec==2024.6.1
    - gymnasium==0.29.1
    - jinja2==3.1.4
    - joblib==1.4.2
    - markupsafe==2.1.5
    - more-itertools==10.3.0
    - mpmath==1.3.0
    - networkx==3.3
    - numpy==2.0.0
    - packaging==24.1
    - plotly==5.22.0
    - pygame==2.6.0
    - scipy==1.14.0
    - sympy==1.13.0
    - tenacity==8.5.0
    - torch==2.3.1
    - tqdm==4.66.4
    - typing-extensions==4.12.2