FROM debian:bookworm-slim as build

RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y git-core
RUN apt-get install -y build-essential
# python deps
RUN apt-get install -y libssl-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y liblzma-dev
RUN apt-get install -y libffi-dev
RUN apt-get install -y libsqlite3-dev
RUN apt-get install -y libncursesw5-dev
RUN apt-get install -y libreadline-dev
# gym deps
RUN apt-get install -y virtualenvwrapper
RUN apt-get install -y swig
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /.setup
RUN git clone https://github.com/pyenv/pyenv.git
ENV PYENV_ROOT=/.setup/pyenv
ENV PATH=${PYENV_ROOT}/shims:${PYENV_ROOT}/bin:${PATH}
ARG PYENV_VERSION=3.11.0
ENV PYENV_VERSION=$PYENV_VERSION
RUN pyenv install ${PYENV_VERSION}
RUN pyenv global ${PYENV_VERSION}

RUN python -m pip install --upgrade pip --compile
RUN python -m pip install torch --compile
RUN python -m pip install gym --compile
RUN python -m pip install gymnasium[all] --compile
RUN python -m pip install more-itertools --compile
RUN python -m pip install joblib --compile
RUN python -m pip install plotly --compile
RUN python -m pip check

VOLUME /src
ENV PYTHONPATH=${PYTHONPATH}:/src

VOLUME /scripts
WORKDIR /scripts
